.PHONY: build-SyncFunction

build-SyncFunction:
	pip install -r requirements.txt -t $(ARTIFACTS_DIR)
	mkdir -p $(ARTIFACTS_DIR)/asken_garmin_sync
	cp *.py $(ARTIFACTS_DIR)/asken_garmin_sync/
	cp -r utils $(ARTIFACTS_DIR)/
